name: Build P-Type Multi-Platform

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: Windows
            ext: .exe
          - os: macos-latest
            platform: macOS
            ext: ''
          - os: ubuntu-latest
            platform: Linux
            ext: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller pillow numpy

    - name: Create data directory
      shell: bash
      run: |
        mkdir -p data

    - name: Create icon (Windows)
      if: runner.os == 'Windows'
      shell: python
      run: |
        from PIL import Image
        import os
        os.makedirs('assets/images', exist_ok=True)
        # Create simple icon if spaceship_icon.png doesn't exist
        try:
            img = Image.open('assets/images/spaceship_icon.png')
        except:
            img = Image.new('RGBA', (64, 64), (138, 43, 226, 255))
        img.save('assets/images/ptype.ico', format='ICO', sizes=[(16,16), (32,32), (64,64), (256,256)])

    - name: Build Windows
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --name PType --icon=assets/images/ptype.ico --add-data "assets;assets" --add-data "data;data" --hidden-import=numpy ptype.py

    - name: Build macOS
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --name PType --add-data "assets:assets" --add-data "data:data" --hidden-import=numpy ptype.py

    - name: Build Linux
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed --name PType --add-data "assets:assets" --add-data "data:data" --hidden-import=numpy ptype.py

    - name: Package Windows
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -Path dist/PType.exe -DestinationPath PType-${{ matrix.platform }}.zip
      shell: pwsh

    - name: Package macOS/Linux
      if: runner.os != 'Windows'
      run: |
        cd dist && tar -czf ../PType-${{ matrix.platform }}.tar.gz PType${{ matrix.ext }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PType-${{ matrix.platform }}
        path: PType-${{ matrix.platform }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          PType-Windows/PType-Windows.zip
          PType-macOS/PType-macOS.tar.gz
          PType-Linux/PType-Linux.tar.gz
        body: |
          # P-Type - The Typing Game
          
          ## Downloads
          - **Windows**: PType-Windows.zip
          - **macOS**: PType-macOS.tar.gz  
          - **Linux**: PType-Linux.tar.gz
          
          ## Features
          - 500+ word dictionary
          - 7 programming languages
          - Boss battles
          - 20 difficulty levels