name: Build Cross-Platform Executables

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            executable_name: P-Type.exe
            artifact_name: P-Type-Windows
          - os: macos-latest
            platform: macos
            executable_name: P-Type
            artifact_name: P-Type-macOS
          - os: ubuntu-latest
            platform: linux
            executable_name: P-Type
            artifact_name: P-Type-Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Build executable (Windows)
      if: matrix.platform == 'windows'
      run: |
        pyinstaller --onefile --windowed --name P-Type ptype.py

    - name: Build executable (macOS)
      if: matrix.platform == 'macos'
      run: |
        pyinstaller --windowed --name P-Type ptype.py

    - name: Build executable (Linux)
      if: matrix.platform == 'linux'
      run: |
        pyinstaller --onefile --name P-Type ptype.py

    - name: Create app bundle (macOS)
      if: matrix.platform == 'macos'
      run: |
        # PyInstaller already created the .app bundle in dist/
        # Just zip it for distribution
        cd dist
        zip -r ../P-Type-macOS.zip P-Type.app

    - name: Upload artifact (Windows/Linux)
      if: matrix.platform != 'macos'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable_name }}

    - name: Upload artifact (macOS)
      if: matrix.platform == 'macos'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: P-Type-macOS.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: P-Type ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## P-Type Game Release
          
          **Cross-platform typing game executables**
          
          ### Downloads:
          - **Windows**: Download `P-Type.exe` and run directly
          - **macOS**: Download `P-Type-macOS.zip`, extract, and run `P-Type.app`
          - **Linux**: Download `P-Type` and run from terminal
          
          ### macOS Users:
          If you get a security warning, right-click the app and select "Open" to bypass Gatekeeper.
          
          ### Changes in this release:
          - Cross-platform typing game
          - Smooth gameplay and sound effects
          - Multiple difficulty levels
        files: |
          artifacts/P-Type-Windows/P-Type.exe
          artifacts/P-Type-macOS/P-Type-macOS.zip
          artifacts/P-Type-Linux/P-Type
