## Removed invalid leading sequence. Workflow must start with 'name:'
name: Build P-Type Multi-Platform

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: Windows
            ext: .exe
          - os: macos-latest
            platform: macOS
            ext: ''
          - os: ubuntu-latest
            platform: Linux
            ext: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Install Python packages (Linux/Windows)
      if: runner.os != 'macOS'
      run: |
        python -m pip install --upgrade pip
        python -m pip install pygame pyinstaller pillow numpy pytablericons

    - name: Install Python packages (macOS)
      if: runner.os == 'macOS'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pygame pyinstaller pillow numpy pytablericons
    - name: Create data directory
      shell: bash
      run: |
        mkdir -p data

    - name: Create icon (Windows)
      if: runner.os == 'Windows'
      shell: python
      run: |
        from PIL import Image
        import os
        os.makedirs('assets/images', exist_ok=True)
        # Create simple icon if spaceship_icon.png doesn't exist
        try:
            img = Image.open('assets/images/spaceship_icon.png')
        except:
            img = Image.new('RGBA', (64, 64), (138, 43, 226, 255))
        img.save('assets/images/ptype.ico', format='ICO', sizes=[(16,16), (32,32), (64,64), (256,256)])

    - name: Build Windows
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --name PType --icon=assets/images/ptype.ico --add-data "assets;assets" --add-data "data;data" --hidden-import=numpy --hidden-import=pytablericons ptype.py

    - name: Build macOS
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --name PType --add-data "assets:assets" --add-data "data:data" --hidden-import=numpy --hidden-import=pytablericons ptype.py

    - name: Build Linux
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed --name PType --add-data "assets:assets" --add-data "data:data" --hidden-import=numpy --hidden-import=pytablericons ptype.py

    - name: Print Linux binary info
      if: runner.os == 'Linux'
      run: |
        file dist/PType
        ldd dist/PType || true
    - name: Print macOS binary info
      if: runner.os == 'macOS'
      run: |
        file dist/PType
        otool -L dist/PType || true

    - name: Package Windows
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -Path dist/PType.exe -DestinationPath PType-${{ matrix.platform }}.zip
      shell: pwsh

    - name: Package macOS/Linux
      if: runner.os != 'Windows'
      run: |
        cd dist && tar -czf ../PType-${{ matrix.platform }}.tar.gz PType${{ matrix.ext }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PType-${{ matrix.platform }}
        path: PType-${{ matrix.platform }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          PType-Windows/PType-Windows.zip
          PType-macOS/PType-macOS.tar.gz
          PType-Linux/PType-Linux.tar.gz
        body: |
          # P-Type v1.5.0 - Explosion & Trivia Edition
          
          ## 🔥 What's New in v1.5.0
          - **Dramatic explosion sounds** when completing words
          - **Trivia System**: Answer questions every 2 boss defeats
          - **Bonus Items**: Collect and use 4 types of power-ups
            - Rapid Fire: Double typing speed
            - Shield Boost: Instant shield points
            - Health Pack: Restore health
            - Time Freeze: Stop all enemies
          - **Enhanced sound effects** with realistic explosions
          - **Professional icons** using pytablericons
          - **7 new achievements** for trivia and bonuses
          
          ## 📥 Downloads
          - **Windows**: PType-Windows.zip
          - **macOS**: PType-macOS.tar.gz  
          - **Linux**: PType-Linux.tar.gz
          
          ## 🎮 Core Features
          - 100 progressive difficulty levels
          - 7 programming languages for practice
          - Aggressive boss AI with smart tracking
          - 19+ unlockable achievements
          - Multiple player profiles
          - Detailed statistics tracking
          - Save/load system
